services:
  traefik:
    restart: on-failure
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=frolprank@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "8090:80"   # Другие порты для избежания конфликтов
      - "8443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
    depends_on:
      - postgres
      - serverpod
    networks:
      - serverpod2-network

  postgres:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped
    image: postgres:15
    labels:
      - "traefik.enable=false"
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - app2_data:/var/lib/postgresql/data
    networks:
      - serverpod2-network

  serverpod:
    restart: unless-stopped
    image: ghcr.io/${GHCR_ORG}/a13_server:latest
    environment:
      SERVERPOD_DATABASE_PASSWORD: ${SERVERPOD_DATABASE_PASSWORD}
      SERVERPOD_DATABASE_HOST: postgres
      SERVERPOD_DATABASE_NAME: ${SERVERPOD_DATABASE_NAME}
      SERVERPOD_DATABASE_USER: ${SERVERPOD_DATABASE_USER}
      SERVERPOD_DATABASE_PORT: 5432
      SERVERPOD_DATABASE_REQUIRE_SSL: false
      SERVERPOD_DATABASE_IS_UNIX_SOCKET: false
      SERVERPOD_SERVICE_SECRET: ${SERVERPOD_SERVICE_SECRET}
      SERVERPOD_MAX_REQUEST_SIZE: ${SERVERPOD_MAX_REQUEST_SIZE}
    command:
      [
        "--mode",
        "production",
        "--server-id",
        "default",
        "--logging",
        "normal",
        "--role",
        "monolith",
        "--apply-migrations",
      ]
    labels:
      - "traefik.enable=true"
      # API маршруты для app2
      - "traefik.http.routers.api2.rule=Host(`api2.my-points.ru`)"
      - "traefik.http.routers.api2.entrypoints=websecure"
      - "traefik.http.routers.api2.service=api2-service"
      - "traefik.http.routers.api2.tls.certresolver=myresolver"
      - "traefik.http.services.api2-service.loadbalancer.server.port=8080"

      # Insights маршруты для app2
      - "traefik.http.routers.insights2.rule=Host(`insights2.my-points.ru`)"
      - "traefik.http.routers.insights2.entrypoints=websecure"
      - "traefik.http.routers.insights2.service=insights2-service"
      - "traefik.http.routers.insights2.tls.certresolver=myresolver"
      - "traefik.http.services.insights2-service.loadbalancer.server.port=8081"

      # Web маршруты для app2
      - "traefik.http.routers.web2.rule=Host(`web2.my-points.ru`)"
      - "traefik.http.routers.web2.entrypoints=websecure"
      - "traefik.http.routers.web2.service=web2-service"
      - "traefik.http.routers.web2.tls.certresolver=myresolver"
      - "traefik.http.services.web2-service.loadbalancer.server.port=8082"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - serverpod2-network

networks:
  serverpod2-network:
    name: serverpod2-network
    driver: bridge

volumes:
  app2_data: